
spring:
  application:
    name: SimpleOktaSecurity
    instance_id: i001
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/world
    username: root
    password: Nov#2017
    initialize: true
    testWhileIdle: 1
    validationQuery: SELECT 1
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQLDialect
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy    

logging:
  level:
    org.hello.boot.rs.controllers: INFO
    
server:
  port: 8443
  ssl:
    enabled: true
    key-alias: spring
    key-store: src/main/resources/saml/keystore.jks
    key-store-password: secret
security:
  saml2:
    metadata-url: https://dev-513058.oktapreview.com/app/exkdi8ssrc703wnTE0h7/sso/saml/metadata
    
info:
  app:
    name: World RestFul Sevice V2
    description: Detail of Countrys, Citys, Region, Languages .... etc around the world.
    version: 2.0.1
    
entitymanager:
  packagesToScan: org.hello.boot